name: recombination
channels:
  - defaults
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - cxx-compiler
  - cmake=3.19.6
  - protobuf=3.12.3
  - make
  - autoconf
  - boost-cpp
  - mafft
  - python
  - pip
  - git
  - wget
  - rsync
  - openmpi
  - openssh
  - isa-l
  - google-cloud-storage
  - google-cloud-sdk
  - pip:
          - pyyaml
          - chronumental
